name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          # key: ${{ secrets.SERVER_SSH_KEY }}
          # passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }} # optional
          script: |
            # 1. Navigate to the App directory on your server
            cd /root/ib-reminder

            # 2. Pull the latest code
            git reset --hard
            git pull origin main

            # 3. Activate Virtual Environment and install dependencies
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            
            source venv/bin/activate
            pip install -r requirements.txt

            # 4. Configure Nginx
            sudo cp nginx_ibportal.conf /etc/nginx/sites-available/ibportal.opofinance.com
            sudo ln -sf /etc/nginx/sites-available/ibportal.opofinance.com /etc/nginx/sites-enabled/
            sudo nginx -t && sudo systemctl reload nginx

            # 5. Restart the Flask service via PM2
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
